config/routes.rb
CrowdFunder::Application.routes.draw do
  
  root :to => 'projects#index'

  resources :sessions, only: [:create]
  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout
  
  post 'users/:id' => 'users#update'
  resources :users, except: [:index] do
    member do
      get :activate
    end
  end
  resources :projects do
    resources :tiers, except: [:index, :show]
    resources :transactions
  end

  get 'updatetiers' => 'transactions#update_tiers'
  post 'createtransaction' => 'transactions#create'
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :sponsors, through: :transactions, class_name: "User", source: :user
  has_many :tiers
  accepts_nested_attributes_for :tiers
  has_many :transactions
  has_attached_file :projectpicture, styles: { medium: "400x250>", thumb: "100x100>" }, default_url: ActionController::Base.helpers.asset_path('assets/defaultprojectimage.png')

  def sum_raised
    total = 0
    self.transactions.each do |pledge|
      total += pledge.dollar_amount if pledge.dollar_amount
    end
    total
  end

  def percentage_raised
    if self.goal != 0
      ( (self.sum_raised.to_f / self.goal) * 100 ).to_i
    else
      0
    end
  end

  def active
    (self.percentage_raised < 100) && (self.end_date >= DateTime.now)
  end

  def number_of_backers
    a = self.transactions.select{|transaction| !transaction.dollar_amount.nil?}
    a.uniq! { |p| p.user_id }
    a.count
  end

  def number_of_transactions
    self.transactions.select{|transaction| !transaction.dollar_amount.nil?}.size
  end

end

app/models/tier.rb
class Tier < ActiveRecord::Base
  belongs_to :project
  has_many :transactions

  def qty_remaining
    self.initial_quantity - self.transactions.size
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :tier

  def qualified_tiers(project, amount)
    qualified = []
    project.tiers.each do |tier|
      qualified << tier if amount >= tier.threshold && tier.qty_remaining > 0
    end
    qualified 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_attached_file :avatar, 
  									styles: { medium: "300x300#",
                              thumb: "100x100#",
                              mini: "28x28#" },
  									default_url: ActionController::Base.helpers.asset_path('assets/placeholder_:style.png')
                    # Not sure why the asset_path isn't working without setting the 'assets/' - it works in console

  # creating a new user
	validates :password, length: { minimum: 3 }, :on => :create
	validates :password, confirmation: true, :on => :create
	validates :email, :username, :password, on: :create, presence: true

	# updating an existing user - but only check this if password is provided
	validates :password, length: { minimum: 3 }, :on => :update, :if => :password_is_present?
	validates :password, confirmation: true, :on => :update, :if => :password_is_present?

  validates :email, :username, uniqueness: true

  has_many :created_projects, class_name: "Project", foreign_key: 'creator_id'
  has_many :transactions
  has_many :sponsored_projects, through: :transactions, class_name: "Project", source: :project
  
  def password_is_present?
  	password.present?
  end

  def username_is_butt?
    username == "butt"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private
  
	def not_authenticated
	  redirect_to projects_path, alert: "Please login first"
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	skip_before_filter :require_login, only: [:index, :show]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @transaction = @project.transactions.build
  end

  def new
    @creator = current_user
    @project = Project.new({
      creator_id: @creator.id,
    })
    render "edit"
  end

  def create
    @creator = current_user
    @project = @creator.created_projects.build(project_params) #sets creator_id properly
    if @project.save
      redirect_to projects_path
    else
      render "new"
    end
  end

  
     
  def edit
    @project = Project.find(params[:id])
    @creator = @project.creator
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      @transaction = @project.transactions.build
      render :show
    end
  end

  def destroy
  end

  private

  def project_params
    params.require(:project).permit(:name,:goal,:description,:projectpicture,:img,:end_date,:min_pledge,:website,:creator_id,tiers_attributes: [:id, :threshold, :reward_text, :initial_quantity])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:username], params[:password])
      redirect_to projects_path, :flash => { :success => "Login successful!" }
    else
      flash.now[:alert] = "Login failed"
      redirect_to projects_path, :flash => { :warning => "Login failed!" }
    end
  end

  def destroy
    logout
    redirect_to projects_path, notice: 'Logged out!'
  end
end

app/controllers/tiers_controller.rb
class TiersController < ApplicationController
  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :require_login

  def create
    @transaction = Transaction.new
    @project = Project.find(params[:project])
    @transaction.project_id = params[:project]
    @transaction.dollar_amount = params[:amount].to_i
    @transaction.user_id = current_user.id
    @transaction.tier_id = params[:tier]
    @transaction.save
    render :nothing => true
  end

  def update_tiers
    @project = Project.find(params[:project].to_i)
    @transaction = Transaction.new
    @amount = params[:amount].to_i
    respond_to do |format|
      format.js {}
    end
  end

  private
  def transaction_params
    params.require(:transaction).permit(:amount, :project, :tier, :dollar_amount)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:new, :create, :activate]

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(projects_path, :notice => 'Your account was successfully activated.')
    else
      not_authenticated
    end
  end

  def show
    @active_projects_transactions = @user.transactions.select {|transaction| transaction.project.active}
    @completed_projects_transactions = @user.transactions.select {|transaction| !transaction.project.active}
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(projects_path, notice: 'Please check your email for an account activation link') }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { render json: user_params }
      else
        format.html { render action: 'show' }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  private
    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :first_name, :last_name, :street_address, :city, :province, :postal_code, :phone_number, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def days_remaining(end_date)
		distance_of_time_in_words(DateTime.now, end_date).to_s.capitalize
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CrowdFunder" %></title>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
      
      <!-- Site Title -->
      <ul class="title-area">
        <li class="name">
          <h1><a href="<%= root_path %>">CrowdFunder</a></h1>
        </li>

        <!-- Mobile Menu Toggle -->
        <li class="toggle-topbar menu-icon">
          <a href="#">
            <span>Menu</span>
          </a>
        </li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">

          <!-- If logged in -->
          <% if current_user %>


            <!-- Edit Profile -->
            <ul class="left">
              <li>
              <a href="<%= user_path(current_user.id) %>">
              <%= image_tag current_user.avatar.url(:mini) %> &nbsp; <%= current_user.username %>
              </a>
              </li>
            </ul>

            <!-- new proj -->
            <a href="<%= new_project_path %>" class="button success tiny left">New Project</a>

            <!-- Logout Button -->
            <li class="has-form">
                <%= link_to "Logout", :logout, method: :post, class: "button" %>
            </li>

          <!-- If logged out or unregistered -->
          <% else %>
            
            <!-- Login Form -->
            <li class="has-form">
              <div class="row collapse">
                <%= form_tag (sessions_path), method: :post do %>
                  <div class="large-5 small-5 columns">
                    <%= text_field_tag :username, nil, placeholder: "Username" %>
                  </div>
                  <div class="large-5 small-5 columns">
                    <%= password_field_tag :password, nil, placeholder: "Password" %>
                  </div>
                  <div class="large-2 small-2 columns">
                    <%= submit_tag "Login", class: "button expand", id: "submit-login" %>
                  </div>
                <% end %>
              </div>
            </li>
            
            <!-- <li class="divider"></li> -->
            
            <!-- Register Button -->
            <li class="has-form">
              <%= link_to "Register", new_user_path, class: "alert button expand" %>
            </li>
          <% end %>
        </ul>

        <ul class="left">

        <li class="has-dropdown">
          <%= link_to "Projects", projects_path %>
          <ul class="dropdown">
            <li><%= link_to "View all Projects", projects_path %></li>
            <li><%= link_to "Create a Project", new_project_path %></li>
          </ul>
        </li>
        </ul>

      </section>
    </nav>
  </div>

    <% if flash[:notice] %>
      <div data-alert class="alert-box info">
        <%= flash[:notice] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% elsif flash[:warning] %>
      <div data-alert class="alert-box warning">
        <%= flash[:warning] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% elsif flash[:success] %>
      <div data-alert class="alert-box success">
        <%= flash[:success] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>

    <div class="row">
      <div class="small-12 columns">
        <main>

          <%= yield %>
          
        </main>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/projects/_dynamictiers.html.erb
<%= p.fields_for :tiers do |t| %>
  <li class="tiercard">
    <div class="tiernumber">
      <h4 class="inline threshold nopad">$ Threshold:<%= t.text_area :threshold %></h4>
    </div>
    <h5 class="remaining">Quantity:<%= t.text_area :initial_quantity%></h5>
    <p class="tiertext"><%= t.text_area :reward_text %></p>
    <button class="tierdelete">Remove this tier</button>
  </li>
<% end %>

app/views/projects/edit.html.erb
<%= form_for @project, html: {multipart: true} do |p| %>
  <h1><%= p.text_area :name, placeholder: "Type your project name here!" %> <small class="subheader">by <%= @creator.username %></h1>


  <div class="large-9 columns">

    <div class="leftcoltop leftcol">
       <%= p.text_area :summary, placeholder: "Type a short summary here"%>
      <div class="headerimg" style="background-image:url(<%= @project.projectpicture.url %>)"></div>
      
      <div class="goals">
        <h3 class="center round progress100">Funding Goal:<%= p.text_area :goal %></h3>
        <h3 class="center round progress100">End Date:<%= p.date_field :end_date %></h3> 
        <%= p.submit "Save Changes", class: "button large alert contbutton" %>
      </div>
      <%= p.file_field :projectpicture %>
    </div>

    <div class="leftcolmid leftcol">
      <h3>Description</h3>
      <p class="text-justify"><%= p.text_area :description, placeholder: "Type your project description here! Be specific and reference excellent buzzwords." %></p>
    </div>

    <div class="leftcolbottom leftcol panel">
      <h3>About The Creator</h3>
      <p>
        <h5><%= @project.creator.username %> <small><%= mail_to @project.creator.email %></small></h5>
        <ul style="list-style-type:none;">
          <li><b>Projects: </b><%= @project.creator.created_projects.size %></li>
        </ul>
      </p>
    </div>
  </div>




  <div class="large-3 columns" id="rightcol">
    <ul id="tierlist">
      <%= render "dynamictiers", p: p %>
    </ul>
    <button id="tieradd">Add a new reward tier</button>
  </div>
<% end %>

app/views/projects/index.html.erb
<div class="large-12">

  <ul class="orbit" data-orbit data-options="animation:slide;
                                            bullets:false;
                                            slide_number:false;
                                            timer_speed: 2000;
                                            animation_speed: 1000;
                                            next_on_click: true;
                                            variable_height: false; ">
    <% @projects.each do |project| %>
      <li class="test">
        <a href="<%= project_path(project) %>">
          <% if project.projectpicture.url == "/assets/defaultprojectimage.png" %>
            <div class="orbitslide" style="background-image:url(<%= project.img %>)"></div>
          <% else %>
            <div class="orbitslide" style="background-image:url(<%= project.projectpicture.url %>)"></div>
          <% end %>
        </a>
        <div class="orbit-caption">
          <%= project.name %>
        </div>
      </li>
    <% end %>
  </ul>


 <% @projects.each do |project| %>
  <a href="<%= project_path(project) %>">
    <% if project.projectpicture.url == "/assets/defaultprojectimage.png" %>
      <div class="indexcard" style="background-image:url(<%= project.img %>)">
        <h3 class="indexcardtitle"><%= project.name %><h3>
        <h3 class="indexcardsummary"><%= project.summary %></h3>
      </div>
    <% else %>
      <div class="indexcard" style="background-image:url(<%= project.projectpicture.url %>)">
        <h3 class="indexcardtitle"><%= project.name %><h3>
        <h3 class="indexcardsummary"><%= project.summary %></h3>
      </div>
    <% end %>
      
    
  </a>
 <% end %>

</div>

app/views/projects/show.html.erb
<h1><%= @project.name %> <small class="subheader">by <%= @project.creator.username %></h1>

<div id="addfundsmodal" class="reveal-modal" data-reveal>
  <h2><small>Contribute to</small> <span style="color:#3c7df0"><%= @project.name %></span></h2>
  <%= form_for [@project, @transaction] do |t| %>
    <%= t.number_field :dollar_amount, class: "dollar_amount", placeholder: "Please enter an amount..." %>
  <% end %>
  <div class="tierselect"></div>
  <a class="close-reveal-modal">&#215;</a>
</div>

<div class="large-9 columns">

  <div class="leftcoltop leftcol panel">
    <div class="headerimg" style="background-image:url(<%= @project.projectpicture.url %>)"></div>
    <div class="goals">
      <h3 class="center round progress100"><%= @project.percentage_raised %>% of <%= number_to_currency @project.goal.to_s, precision: 0 %></h3>
        <% if @project.percentage_raised < 100 %>
          <div class="progress round">
          <span class="meter" style="width: <%= @project.percentage_raised %>%"></span>
        <% else %>
          <div class="progress success round">
          <span class="meter win" style="width: 100%"></span>
        <% end %>
      </div>
      <p class="subheader center backtrans"><small><%= number_to_currency @project.sum_raised, precision: 0 %> from <%= pluralize @project.number_of_backers, 'backer' %><br>and <%= pluralize @project.number_of_transactions, 'transaction' %></small></p>
      <% if current_user %>
        <% if current_user.id == @project.creator.id %>
          <a href="/projects/<%=@project.id%>/edit" class="button large alert contbutton">Edit Project</a>
        <% else %>
          <a href="#" data-reveal-id="addfundsmodal" class="button large alert contbutton">Contribute</a>
        <% end %>
      <% else %>
        <a href="#" data-reveal-id="addfundsmodal" class="button large alert contbutton">Contribute</a>
      <% end %>
    </div>
  </div>

  <div class="leftcolmid leftcol panel">
    <h3>End Date</h3>
    <p><%= distance_of_time_in_words_to_now(@project.end_date) %></p>
    <h3>Summary</h3>
    <p class="text-justify"><%= @project.summary %></p>
    <h3>Description</h3>
    <p class="text-justify"><%= @project.description %></p>
  </div>

  <div class="leftcolbottom leftcol panel">
    <h3>About The Creator</h3>
    <p>
      <h5><%= @project.creator.username %> <small><%= mail_to @project.creator.email %></small></h5>
      <ul style="list-style-type:none;">
        <li><b>Projects: </b><%= @project.creator.created_projects.size %></li>
      </ul>
    </p>
  </div>

</div>


<div class="large-3 columns" id="rightcol">
    <% if @project.tiers.count == 0 %>

    <ul>
      <li class="tiercard">
        <h5 style="color:#ffffff">No tiers set for this project</h5>
      </li>
    </ul>

    <% else %>

      <% @project.tiers.sort { |e, b| e.threshold <=> b.threshold }.each do |tier| %>
        <% if tier.qty_remaining < 1 %>
          <ul>
            <li class="tiercard_out">
            <div class="tiernumber">
              <%= image_tag "star.png", class: "starimg" %>
              <h4 class="inline threshold nopad">$<%= tier.threshold.to_s %></h4>
            </div>
            <h5 class="remaining_none">Sold Out!</h5>
              <p class="tiertext_out"><%= tier.reward_text %></p>
            </ul>    
          <% else %>
            <ul>
            <li class="tiercard">
            <div class="tiernumber">
              <%= image_tag "star.png", class: "starimg" %>
              <h4 class="inline threshold nopad"><%= number_to_currency tier.threshold.to_s, precision: 0 %></h4>
            </div>
            <h5 class="remaining"><%= tier.qty_remaining %> remaining</h5>
            <p class="tiertext"><%= tier.reward_text %></p>
          </ul>
        <% end %>
      <% end %>
      </ul>

    <% end %>
</div>

app/views/transactions/_tierselect.html.erb
<% if @transaction.qualified_tiers(@project, @amount).count == 0 %>
<div class="tier_return_none">
  <% if @project.tiers.count > 0 %>
    <p>Please enter a larger amount to qualify for a tier reward</p>
  <% end %>
</div>
<% else %>
  <p class="subheader" style="font-weight:200;margin-bottom:10px;">Please select a tier reward...</p>

  <% @transaction.qualified_tiers(@project, @amount).each do |tier| %>
  <div class="tier_return" href="#" id="<%= tier.id %>">
    <div class="tier_return_threshold"><%= image_tag "star.png", class: "starimgpop" %> $<%= tier.threshold %></div>   
    <div class="tiernumber" style="margin-bottom:5px;"><%= tier.qty_remaining %> remaining</div>
    <div class="tierreward"><%= tier.reward_text %></div>
  </div>
  <% end %>

<% end %>

<a href="#" class="button medium alert contbutton" id="submit_funds">Submit Funds</a>

<script>

$('#submit_funds').on('click', function(event) {
  event.preventDefault();
  $(this).addClass('disabled');
  $(this).html('Submitting...')
  var amount = $('.dollar_amount').val();
  var project = window.location.pathname.replace('/projects/', "");
  var tier = $('.selected').attr('id');
  $.ajax({
    type: "POST",
    url: "/createtransaction",
    dataType: 'script',
    data: {amount: amount,
          project: project,
          tier: tier},
    success: ""
  });
  setTimeout(function () {
    location.reload();
  }, 1000);
});

</script>

app/views/transactions/update_tiers.js.erb
$('.tierselect').html("<%= escape_javascript(render(partial: 'tierselect')) %>");

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="row">
    <div class="small-8">
      <div class="row">
        <div class="small-3 columns">
          <%= f.label :username, for: "right-label", class: "right inline" %>
        </div>
        <div class="small-9 columns">
          <%= f.text_field :username, id: "right-label", placeholder: "" %>

        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-8">
      <div class="row">
        <div class="small-3 columns">
          <%= f.label :email, for: "right-label", class: "right inline" %>
        </div>
        <div class="small-9 columns">
          <%= f.text_field :email, id: "right-label", placeholder: "" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-8">
      <div class="row">
        <div class="small-3 columns">
          <%= f.label :password, for: "right-label", class: "right inline" %>
        </div>
        <div class="small-9 columns">
          <%= f.password_field :password, id: "right-label", placeholder: "" %>
        </div>
      </div>
    </div>
  </div>  
  <div class="row">
    <div class="small-8">
      <div class="row">
        <div class="small-3 columns">
          <%= f.label "Confirm Password", for: "right-label", class: "right inline" %>
        </div>
        <div class="small-9 columns">
          <%= f.password_field :password_confirmation, id: "right-label", placeholder: "" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-8">
      <div class="row">
        <div class="small-9 small-offset-3 columns">
          <%= f.submit "Register", class: "button tiny" %>
          <%= link_to 'Cancel', root_path, class: "alert button tiny" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_sponsored_project.html.erb
<div class="small-2 columns">
	<%= image_tag(transaction.project.img, class: "th") %>
</div>

<div class="small-4 columns">
	<h4><%= link_to transaction.project.name, project_path(transaction.project) %></h4>
	<h5 class="subheader"><em><%= transaction.project.summary %></em></h5>
	<p><strong>You contributed $<%= transaction.dollar_amount %>.00 on <%= transaction.created_at.strftime("%d-%m-%Y") %></strong></p>
	<% if transaction.tier.present? %>
		<p><strong>Your reward: </strong> <%= transaction.tier.reward_text %></p>
	<% end %>
	<p><small><%= mail_to transaction.project.creator.email, "Contact the project owner" %></small></p>
</div>

app/views/users/_sponsored_project_transaction.html.erb
<div class="small-2 columns">
	<%= image_tag(transaction.project.img, class: "th") %>
</div>

<div class="small-4 columns">
	<h4><%= link_to transaction.project.name, project_path(transaction.project) %></h4>
	<h5 class="subheader"><em><%= transaction.project.summary %></em></h5>
	<p><strong>You contributed $<%= transaction.dollar_amount %>.00 on <%= transaction.created_at.strftime("%d-%m-%Y") %></strong></p>
	<% if transaction.tier.present? %>
		<p><strong>Your reward: </strong> <%= transaction.tier.reward_text %></p>
	<% end %>
	<p><small><%= mail_to transaction.project.creator.email, "Contact the project owner" %></small></p>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<div class="row">
  <div class="small-12 small-centered columns">
  	<h1>Create an Account</h1>
		<%= render 'form' %>
  </div>
</div>